### PR TITLE
deps: upgrade http-errors

### PR DESCRIPTION
**Pull request by dead-horse**

### CODE REVIEW

**Comment by dougwilson** [comment]
@jonathanong since you assigned this to me, I'll go ahead and get this out over the coming minutes.

**Comment by jonathanong** [comment]
@dougwilson thanks Doug! let me know if I can help with anything

**Comment by dougwilson** [comment]
👍 just bringing this to look like the other mods in `jshttp`

**Comment by yuhongshuai** [comment]
use fetch function instand of $.ajax in client, resolve the problem( 422 (Unprocessable Entity) ;)

**Pull request closed without merging**
